version: "1.0"
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: TASK_DEF_ARN
        LoadBalancerInfo:
          ContainerName: chatbot-container
          ContainerPort: 3000
